# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9584bd317ca2db4638f731c1d61dc39dd992a644a5fe16c6ea9e63b42cfe1bc66208e5f7c429eded9bd7ec2eba17269c4cc069956cfc6d69f977c36ec5b96e49

test:
  secret_key_base: 6cb819f6ab06a18fd8a60908f2041eb0579b6b1e0696bf41e755a80c5409befb668f0e76696658147034aac84c8652c4ae5bc01a7b59e7e98e883cfa92477486

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
